### ISSUE TITLE
To do list for 01/17/20

### ISSUE THREAD

**Issue by Monsauce** [Monsauce/frictionless_data_fellowship#1]
- [x] Finish Friday questions

- [ ] Find another resource on reproducible research, open science, or data management and add it to the Fellows Resources site by opening a Pull Request on GitHub

- [x] Finish audience mapping lesson 

- [x] Post data package and code to GitHub

**Comment by Monsauce** [comment]
@lwinfree keep me accountable!

**Comment by lwinfree** [comment]
Hey @Monsauce! Checking in to see how you are progressing? 😃

**Comment by Monsauce** [comment]
@lwinfree I finished all except adding the resource. Opened up a new issue for my to do list for this week. Thanks for checking in on me :)
